dist: trusty
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc

sudo: required

addons:
  apt:
    update: true
    packages:
    - cmake
    - libasound2-dev
    - libsqlite3-dev
    - wget

script:
  - pwd

  - sudo sh build.sh

  - mkdir build-mediastream && cd build-mediastream
  - cmake ..
  - sudo make install

  - mediastreamer2_tester --resource-dir /usr/local/share/mediastreamer2_tester/sounds/ --writable-dir ~/